version: "3.9"  # optional since v1.27.0
services:
  email-weather:
    build: .
    # init: true
    volumes:
      - type: volume
        source: data-volume
        target: /data-volume
        volume:
          nocopy: true
    environment:
      DATA_DIR: /data-volume
      SECRETS_DIR: /tmp/secrets
      CLIENT_SECRET:
      TOKEN_CACHE:

volumes:
  data-volume:
