name: Docs on GitHub Pages

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  build:
    name: Build/check docs site
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          BUILD_DIR: docs
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
  build_and_deploy:
    name: Publish docs site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout main
      uses: actions/checkout@v3.0.0
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.16.1
      env:
        BUILD_DIR: docs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
